# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/april-wallpaper-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "mobaijun8@163.com"
         git config --local user.name "mobaijun"
         git pull
         git add README.md
         git add wallpaper.md
         git add picture/*
         git add api/*
         git add api.json
         git commit -m ":sparkles: update today wallpaper"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GIT_TOKEN }}
         branch: main
